---
- name: "Setup.yml"
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:

  - name: Enable root SSH login
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin yes"
      state: present

  - name: Enable password SSH login
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin yes"
      state: present

  - name: Restart service ssh
    ansible.builtin.service:
      name: sshd
      state: restarted

  - name: Upgrade all packages
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bash-completion
      - curl
      - git
      - net-tools
      - wget

  - name: Install dependencies for VirtualBox Guest Additions
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - build-essential
      - dkms
      - make
      - "linux-headers-{{ ansible_kernel }}"
    when:
      - ansible_virtualization_type == "virtualbox"

  - name: Download VBoxGuestAdditions.iso
    get_url:
      url: https://download.virtualbox.org/virtualbox/7.0.18/VBoxGuestAdditions_7.0.18.iso
      dest: /tmp/VBoxGuestAdditions.iso
      mode: '0644'
    when: ansible_virtualization_type == "virtualbox"

  - name: Mount VBoxGuestAdditions.iso
    mount:
      path: /mnt
      src: /tmp/VBoxGuestAdditions.iso
      fstype: iso9660
      opts: ro,loop
      state: mounted
    when: ansible_virtualization_type == "virtualbox"

  - name: Install VBoxGuestAdditions.iso
    command: sh /mnt/VBoxLinuxAdditions.run
    register: vbox_result
    failed_when: "'Running kernel modules will not be replaced until \nthe system is restarted' not in vbox_result.stdout"
    when: ansible_virtualization_type == "virtualbox"

  - name: Umount VBoxGuestAdditions.iso
    mount:
      path: /mnt
      state: absent
    when: ansible_virtualization_type == "virtualbox"

  - name: Delete VBoxGuestAdditions.iso
    file:
      path: /home/packer/VBoxGuestAdditions.iso
      state: absent
    when: ansible_virtualization_type == "virtualbox"